version: '3'

services:
  redis:
    image: redis:latest
    container_name: iss-redis
    volumes:
      - ./data:/data
    user: "1000:1000"
    command: redis-server --appendonly yes --dir /data
    networks:
      - iss-network

  flask:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    image: username/iss_tracker:1.0
    container_name: iss-tracker-flask
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - iss-network

networks:
  iss-network:
    driver: bridge